apiVersion: v1
kind: Namespace
metadata:
  name: tanawith
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tanawith
  name: eshoponweb-deployment
  labels:
    app: eshoponweb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: eshoponweb
        # service: webapp
    spec:
      containers:
        - name: eshoponweb-app
          image: aistraining.azurecr.io/eshoponweb-webapp-tanawith:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
